### PR TITLE
why 100vh for a button?

### PR DESCRIPTION
**Pull request by jpmedeirosmorais**

### CODE REVIEW

**Comment by awran5** [comment]
Hello @jpmedeirosmorais Its applied to the main container `floatingWhatsapp` not to button in which to make sure that the chat box will open properly.
[width: auto](https://stackoverflow.com/questions/17468733/difference-between-width-auto-and-width-100-percent) will keep the element width same as its **parent** so if the `Component` is nested to an element that has a fixed width, the chat box will not open.

**Comment by jpmedeirosmorais** [comment]
Okay, but the floating button(when it is instanceated)makes a big space
between it and the next component.

Em sáb., 18 de set. de 2021 16:45, Ahmed Khalil ***@***.***>
escreveu:

**Comment by awran5** [comment]
Would you please show an example? You could use [codesandbox](https://codesandbox.io/)

**Comment by jorgemndoza** [comment]
I had the same issue. I had to copy the css file and remove the full height.

image

**Comment by jpmedeirosmorais** [comment]
Very good! it worked for me too. Thank you very much, @jorgemndoza!

**Comment by awran5** [comment]
Hey guys .. Thank you for help

@jpmedeirosmorais Indeed, you were right, I just released a new version `v4.0.5` with cool new features, please try it out.

**Comment by jorgemndoza** [comment]
@jpmedeirosmorais You're welcome. 
@awran5 Good job and thanks for creating this package.

**Pull request closed without merging**
